Autoupdate pre-commit
thoth-station/common pull request #1250
Opened 2022-04-06 20:32 UTC by xtuchyna

## Related Issues and Dependencies
None

## This introduces a breaking change

- [ ] Yes
- [X] No

## Description
SSIA

2022-04-06 20:32 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **sesheta** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @sesheta` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fcommon).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/common/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["sesheta"]} -->

2022-04-06 20:33 UTC, xtuchyna commented
@harshad16 do we have some issue tracking the required `autoupdate` for `pre-commit` ?

2022-04-06 20:34 UTC, sesheta commented
@xtuchyna: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 9c87ab58ecfcdda111568d5ae97e892053bcb2f6 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_common/1250/pre-commit/1511804448492490752) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=common&pr=1250). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Axtuchyna). Please help us and [open an issue](https://github.com/thoth-station/common/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-06 21:10 UTC, sesheta commented
@xtuchyna: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 53b4441435866c51cf6d9595ed6cb60469f36a96 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_common/1250/pre-commit/1511810367074865152) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=common&pr=1250). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Axtuchyna). Please help us and [open an issue](https://github.com/thoth-station/common/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-07 10:17 UTC, sesheta commented
@xtuchyna: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | d2b808ba80ab77fa96ae9df3f6182b272133586a | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_common/1250/pre-commit/1512010266345213952) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=common&pr=1250). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Axtuchyna). Please help us and [open an issue](https://github.com/thoth-station/common/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-07 10:25 UTC, harshad16 commented
> Do we have some issue tracking the required `autoupdate` for `pre-commit` ? Also for prow image tags?

No that i know about, feel free to open one @xtuchyna 
cc: @codificat

2022-04-07 10:35 UTC, sesheta commented
@xtuchyna: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 4e55302599a1be8e65644dd68e60e96533adc0ba | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_common/1250/pre-commit/1512014873343561728) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=common&pr=1250). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Axtuchyna). Please help us and [open an issue](https://github.com/thoth-station/common/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-07 15:51 UTC, harshad16 requested changes
all looks good to me
small suggestion for timebeing

2022-04-07 15:51 UTC, harshad16 commented on .pre-commit-config.yaml
>    - repo: https://github.com/pre-commit/mirrors-mypy
my suggestion for now. 
let's remove mypy out of pre-commit and can add it as a separate check like this https://github.com/thoth-station/messaging/blob/82588c945130172f0db76d81a55ea015dabea79e/.prow.yaml#L22
so our pr is not on hold just for mypy

2022-04-07 15:51 UTC, harshad16 commented on Pipfile
> +types-setuptools = "*"
lets remove these bit for now

2022-04-07 15:51 UTC, harshad16 commented on Pipfile
> +types-setuptools = "*"
lets remove these bit for now

2022-04-07 15:53 UTC, sesheta commented
@xtuchyna: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 08ae5e08100b0c7fe55bf6ffbafb2fccbaa98be0 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_common/1250/pre-commit/1512094771500290048) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=common&pr=1250). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Axtuchyna). Please help us and [open an issue](https://github.com/thoth-station/common/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-12 11:01 UTC, harshad16 commented
Already merged following commit via https://github.com/thoth-station/common/pull/1253

2022-04-12 11:01 UTC, closed without merging