bump kubernetes version for common image
thoth-station/common pull request #1254
Opened 2022-04-11 15:49 UTC by Gregory-Pereira

## Related Issues and Dependencies

Addresses: https://github.com/thoth-station/common/issues/1251

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Bumping version of PyYaml (which depends on Kubernetes, which depends on openshift) for CVE_2020_1747

2022-04-11 15:49 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **fridex** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @fridex` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fcommon).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/common/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fridex"]} -->

2022-04-11 15:49 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pytest | bed548af7aa13dd48f8f447557bebcb529c3701b | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_common/1254/thoth-pytest-py38/1513544730653233152) | true | `/test thoth-pytest-py38`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=common&pr=1254). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/common/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-11 15:54 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pytest | bed548af7aa13dd48f8f447557bebcb529c3701b | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_common/1254/thoth-pytest-py38/1513544730653233152) | true | `/test thoth-pytest-py38`
aicoe-ci/prow/pre-commit | bed548af7aa13dd48f8f447557bebcb529c3701b | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_common/1254/pre-commit/1513544730233802752) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=common&pr=1254). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/common/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-11 19:15 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pytest | bed548af7aa13dd48f8f447557bebcb529c3701b | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_common/1254/thoth-pytest-py38/1513544730653233152) | true | `/test thoth-pytest-py38`
aicoe-ci/prow/pre-commit | bf5513eeb9b644fe8aaac72bcb6802254e014c23 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_common/1254/pre-commit/1513596583487213568) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=common&pr=1254). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/common/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-11 19:18 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | bf5513eeb9b644fe8aaac72bcb6802254e014c23 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_common/1254/pre-commit/1513596583487213568) | true | `/test pre-commit`
aicoe-ci/prow/pytest | bf5513eeb9b644fe8aaac72bcb6802254e014c23 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_common/1254/thoth-pytest-py38/1513596583994724352) | true | `/test thoth-pytest-py38`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=common&pr=1254). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/common/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-11 19:28 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | bf5513eeb9b644fe8aaac72bcb6802254e014c23 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_common/1254/pre-commit/1513596583487213568) | true | `/test pre-commit`
aicoe-ci/prow/pytest | 22b467dabfa6575e1e2abb46d735a32c4978112e | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_common/1254/thoth-pytest-py38/1513599168524849152) | true | `/test thoth-pytest-py38`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=common&pr=1254). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/common/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-11 19:30 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pytest | 22b467dabfa6575e1e2abb46d735a32c4978112e | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_common/1254/thoth-pytest-py38/1513599168524849152) | true | `/test thoth-pytest-py38`
aicoe-ci/prow/pre-commit | 22b467dabfa6575e1e2abb46d735a32c4978112e | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_common/1254/pre-commit/1513599160136241152) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=common&pr=1254). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/common/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-11 19:36 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 22b467dabfa6575e1e2abb46d735a32c4978112e | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_common/1254/pre-commit/1513599160136241152) | true | `/test pre-commit`
aicoe-ci/prow/pytest | 960039dcc9ed105f275bc97490d1a09b786bd42e | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_common/1254/thoth-pytest-py38/1513601154108362752) | true | `/test thoth-pytest-py38`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=common&pr=1254). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/common/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-12 11:02 UTC, harshad16 requested changes
please revert pre-commit chnages

2022-04-25 11:26 UTC, harshad16 requested changes
All lgtm
can you please rebase your PR that would get to 1 commit 
and also one suggestion.

2022-04-25 11:26 UTC, harshad16 commented on Pipfile
> +openshift = "==0.12.0"
```suggestion
openshift = "~=0.12.0"
```
How about this https://github.com/openshift/openshift-restclient-python/tree/v0.12.1
It has some changes: https://github.com/openshift/openshift-restclient-python/commits/v0.12.1

2022-04-28 13:46 UTC, fridex approved these changes
Changes look good to me. I've also tried to verify that the common library is still able to schedule workfload in the cluster. No issues observed, but we should keep an eye on this change. 👍🏻

2022-04-28 13:46 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/common/pull/1254#pullrequestreview-956469193" title="Approved">fridex</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fcommon).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/common/blob/master/OWNERS)~~ [fridex]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-04-28 13:49 UTC, merged